config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :posts do
    resources :comments
  end

  resources :indications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/indication.rb
class Indication < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :indications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/indications_controller.rb
class IndicationsController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show; end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/indications_helper.rb
module IndicationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .content
    %p.comment_content= comment.comment
    %p.comment_author= comment.user.email
    %p{:style => "font-family:courier; font-size:70%;"}
      Publicado há
      \#{time_ago_in_words(comment.created_at)}
  .buttons
    = link_to "Editar", edit_post_comment_path(comment.post, comment)
    = link_to "Deletar", [comment.post, comment], method: :delete, data: { confirm: "Confirmar deleção?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
 = f.input :comment
 = f.submit

app/views/comments/edit.html.haml
%h1 Editar resposta

= simple_form_for([@post, @comment]) do |f| 
  = f.input :comment
  = f.submit

app/views/home/index.html.haml
!!!
%html
  %body
    %hr/
    .wrapper
      .row.no-gutters.bg-light.position-relative
        .col-md-6.mb-md-0.p-md-5
          = image_tag "bar.png"
        .col-md-6.position-static.p-4.pl-md-0
          %h5.mt-0 Fórum
          %p Lorem ipsum
          %a.stretched-link{href: "posts"} Me leve ao fórum
      %p
      .row.no-gutters.bg-light.position-relative
        .col-md-6.mb-md-0.p-md-5
          = image_tag "bar.png"
        .col-md-6.position-static.p-4.pl-md-0
          %h5.mt-0 Produtos
          %p Lorem ipsum
          %a.stretched-link{href: "#"} Me leve
      %p
      .row.no-gutters.bg-light.position-relative
        .col-md-6.mb-md-0.p-md-5
          = image_tag "bar.png"
        .col-md-6.position-static.p-4.pl-md-0
          %h5.mt-0 Indicaí
          %p Lorem ipsum
          %a.stretched-link{href: "indications"} Me leve
      %p
      .row.no-gutters.bg-light.position-relative
        .col-md-6.mb-md-0.p-md-5
          = image_tag "bar.png"
        .col-md-6.position-static.p-4.pl-md-0
          %h5.mt-0 Curiosidades do mundo felino
          %p Lorem ipsum
          %a.stretched-link{href: "#"} Me leve
      %p
      .row.no-gutters.bg-light.position-relative
        .col-md-6.mb-md-0.p-md-5
          = image_tag "bar.png"
        .col-md-6.position-static.p-4.pl-md-0
          %h5.mt-0 ONGS - Adote ou ajude um miau
          %p Lorem ipsum
          %a.stretched-link{href: "#"} Me leve
      %p

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Universo Gateiro
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", rel: "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Lato", rel: "stylesheet", "type:" => ""}/
    %link{rel: "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %p.notice= notice
      %p.alert= alert
      .wrapper
        = image_tag "bar.png"
      .wrapper
        %nav.navbar.navbar-custom.navbar-expand-lg.navbar-light 
          .container-fluid
            %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavAltMarkup", "data-bs-toggle" => "collapse", type: "button"}
              %span.navbar-toggler-icon
            #navbarNavAltMarkup.collapse.navbar-collapse
              .navbar-nav
                %a.nav-link.active{"aria-current" => "page", href: "../"} Home
                %a.nav-link{href: "/posts"} Fórum
                %a.nav-link{href: "#"} Produtos
                %a.nav-link{href: "/indications"} Indicaí
                %a.nav-link{href: "#"} Curiosicats
                %a.nav-link{href: "#"} ONGs - Adore ou Ajude um miau!
    .container
      = yield

app/views/posts/_form.html.haml
= simple_form_for @post, html: { class: 'form-group' } do |f|
  = f.input :title 
  = f.input :content 
  = f.submit 'Criar'

app/views/posts/edit.html.haml
%h1 Editar
= render 'form'
= link_to 'Voltar', post_path

app/views/posts/index.html.haml
%p
%center
  %h4{:style => "font-family:fantasy;"} Fórum - Universo Gateiro
%hr/
.container
  - if @posts.nil?
    .alert.alert-info.mt-3{:role => "alert"} Nenhum tópico no fórum.
  - else
    %p
      - @posts.each do |post|
        %p{:style => "font-family:courier;"}
          Título:
          %h7{:style => "font-family:courier;"}= link_to post.title.upcase, post
        %p{:style => "font-family:courier; font-size:80%;"}
          Publicado há
          \#{time_ago_in_words(post.created_at)}
          %i
            por #{post.user.email}
        %hr/
%p{:style => "font-family:sans-serif; font-size:90%"}= link_to "Novo Tópico", new_post_path

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
#post_content 
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			Commentários 
		= render @post.comments

		%h3 Responder thread
		= render "comments/form"

	%br/
	%hr/
	%br/	

	= link_to "Editar", edit_post_path(@post), class: "button"
	= link_to "Deletar", post_path(@post), method: :delete, data: { confirm: "Confirmar deleção ?" }, class: "button"